### ISSUE TITLE
✨[feat] : 일반유저의 매물 요청하기 및 요청조회

### ISSUE THREAD

**Issue by sayIshuu** [isa-zip/isa.zip-backend#2]
### 📝 Description
- 일반유저 매물 요청하면 요청정보를 db에 추가한다.
- 일반유저가 요청한 매물들 조건(지역 및 여러 옵션)에 따라 조회할 수 있다.

_추후 매칭에 활용되도록 유의하며 설계해야한다._

---

### 📝 Todo
- [ ] : 일반유저 매물 요청정보 옵션들까지 자동으로 테이블 생성되며 저장
- [ ] : 일반유저 매물 요청 여러 조건(옵션들, 특히 지역)에 따라 필터링 조회 기능
- [ ] : 매물요청정보 통해서 유저 정보 조회하기
