### ISSUE TITLE
🐛 [bug] 일정 관련 로직 수정 및 에러 처리

### ISSUE THREAD

**Issue by 326eunjin** [isa-zip/isa.zip-backend#34]
### 📝 Description

- 현재 일정 등록할때 세부 일정이 동시에 등록되지 않는 이슈가 있어 수정하고자 합니다.
- 일정 등록 관련 에러 처리
- 유저 아이디 가져오는 버그 수정

---

### 📝 Todo

- [ ] : 일정 등록 시, 세부 일정도 동시에 수정되도로고 고치기
- [ ] : 일정 등록 관련 에러 처리
- [ ] : 일반 유저 아이디 가져오는 버그 수정 (-> 로그인한 유저로)
