### ISSUE TITLE
🐛 [fix] : users/items/dong-count 0개일때 안뜨는거, users/items response수정

### ISSUE THREAD

**Issue by sayIshuu** [isa-zip/isa.zip-backend#73]
### 📝 Description

- users/items/dong-count 수정
- users/items 수정

---

### 📝 Todo

**users/items/dong-count**
- [ ] : 해당 지역의 요청이 0개일때 안뜨는 거 수정
- [ ] : 상도동은 뜨는데 상도1동은 안뜨는거 수정
**users/items**
- [ ] : 해당 지역(동)을 요청으로 받고 해당 동 응답만 반환되게 수정
- [ ] : 유저옵션 테이블에 유저아이템 아이디 안들어가는거 수정
